name: fluweather
description: coolweather rewrite by Flutter.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  cookie_jar: ^1.0.1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  dio_http_cache: ^0.2.11
  provider: #latest version
  flukit: #latest version
  cached_network_image: #latest version
  fluttertoast: ^3.1.3
  path: ^1.7.0
  path_provider: ^1.6.24
  google_fonts: ^1.1.1
  pull_to_refresh: ^1.6.3
  get:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets-generator-begin
    # assets/images/*
    - assets/images/ic_partly_cloud_night.png
    - assets/images/bg_cloudy.jpg
    - assets/images/ic_light_snow.png
    - assets/images/ic_partly_cloud_day.png
    - assets/images/ic_dressing.png
    - assets/images/ic_clear_day.png
    - assets/images/ic_ultraviolet.png
    - assets/images/ic_thunder_shower.png
    - assets/images/ic_home.png
    - assets/images/ic_light_haze.png
    - assets/images/ic_clear_night.png
    - assets/images/ic_cloudy.png
    - assets/images/ic_heavy_haze.png
    - assets/images/bg_rain.jpg
    - assets/images/ic_moderate_snow.png
    - assets/images/ic_fog.png
    - assets/images/ic_launcher_foreground.xml
    - assets/images/ic_heavy_snow.png
    - assets/images/bg_clear_day.jpg
    - assets/images/ic_carwashing.png
    - assets/images/ic_moderate_haze.png
    - assets/images/ic_hail.png
    - assets/images/ic_light_rain.png
    - assets/images/ic_coldrisk.png
    - assets/images/bg_fog.jpg
    - assets/images/bg_partly_cloudy_night.jpg
    - assets/images/bg_partly_cloudy_day.jpg
    - assets/images/bg_place.png
    - assets/images/ic_storm_rain.png
    - assets/images/ic_sleet.png
    - assets/images/bg_wind.jpg
    - assets/images/bg_clear_night.jpg
    - assets/images/ic_moderate_rain.png
    - assets/images/bg_snow.jpg
    - assets/images/ic_heavy_rain.png
    - assets/images/ic_launcher_background.xml
    # assets-generator-end

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
